CREATE DATABASE IF NOT EXISTS consultorio CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE consultorio;

CREATE TABLE IF NOT EXISTS events (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    event_date DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);